using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


public enum ecode
{
    ERROR_NONE,
    ERROR_INVALID_OPTION,
    ERROR_UNKNOWN_OPTION,
    ERROR_PATH_UNKNOWN,
    ERROR_DUPLICATE_ARGS,
    ERROR_FILE_NOT_FOUND,
    ERROR_BAD_DEVICE_FILE,
    ERROR_NO_DEVICE_FILE,
    ERROR_BAD_MPU_REGION,
    ERROR_INVALID_DEFINE,
    ERROR_BAD_UKERNEL_REGION,
    ERROR_BAD_GHMB_SIZE,
    ERROR_BAD_PROCESS_STACK,
    ERROR_INSUFFICENT_SRAM,
    ERROR_KREGION_HALF_OVERFLOW,
    ERRRO_SHORT_PROESS_STACK,
    ERROR_COMPLIER_NOT_FOUND,
    ERROR_COMPILATION_ERROR,
    ERROR_MSTACK_SIZE_VIOLATION
};
